name: Run Python Tests

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: install dependencies
        run:  
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: running our test cases with pytest
        run: pytest
